apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-cloud-native-postgresql
  namespace: "opNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloud-native-postgresql
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: k8s.enterprisedb.io/cluster
                operator: Exists
          namespaceSelector: {}
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
      to:
        - podSelector:
            matchLabels:
              apiserver: 'true'
          namespaceSelector: {}
  policyTypes:
    - Egress