apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: cs-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: cs-tenant
  groups:
    - name: cs-volumes
      type: volume
    - excludedResourceTypes:
        - event
        - event.events.k8s.io
        - imagetags.openshift.io
        - pod
        - installplans.operators.coreos.com
        - clients.oidc.security.ibm.com
        - authentication.operator.ibm.com
        - challenges.acme.cert-manager.io
        - orders.acme.cert-manager.io
        - certificaterequests.cert-manager.io
        - clusterserviceversions.operators.coreos.com
        - deployment
      name: cs-resources
      type: resource
    - backupRef: cs-resources
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      name: cs-crd-resources
      type: resource
    - backupRef: cs-resources
      includedResourceTypes:
        - operatorgroups
        - serviceaccount
        - role
        - rolebinding
      name: cs-operator-resources
      type: resource
    - backupRef: cs-resources
      includedResourceTypes:
        - secrets
        - configmaps
        - certificates.cert-manager.io
        - certificates.certmanager.k8s.io
        - issuers.cert-manager.io
        - issuers.certmanager.k8s.io
        - clusters.postgresql.k8s.enterprisedb.io
      name: cs-pre-req-resources
      type: resource
    - backupRef: cs-resources
      excludedResourceTypes:
        - operatorgroups
        - serviceaccount
        - role
        - rolebinding
        - secrets
        - configmaps
        - certificates.cert-manager.io
        - certificates.certmanager.k8s.io
        - issuers.cert-manager.io
        - issuers.certmanager.k8s.io
        - clusters.postgresql.k8s.enterprisedb.io
        - deployments.apps
        - statefulsets.apps
        - daemonsets.apps
        - replicasets.apps
        - controllerrevisions.apps
        - cronjobs.batch
        - jobs.batch
        - challenges.acme.cert-manager.io
        - orders.acme.cert-manager.io
        - certificaterequests.cert-manager.io
        - clusterserviceversions.operators.coreos.com
      name: cs-pre-workload-resources
      type: resource
    - backupRef: cs-resources
      includedResourceTypes:
        - deployments.apps
        - statefulsets.apps
        - daemonsets.apps
        - replicasets.apps
        - controllerrevisions.apps
        - cronjobs.batch
        - jobs.batch
      name: cs-workload-resources
      type: resource
  workflows:
    - failOn: any-error
      name: backup
      sequence:
        - group: cs-volumes
        - group: cs-resources
    - failOn: any-error
      name: restore
      sequence:
        - group: cs-volumes
        - group: cs-crd-resources
        - group: cs-operator-resources
        - group: cs-pre-req-resources
        - group: cs-pre-workload-resources
        - group: cs-workload-resources
