apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpfs-util-role
  namespace: cs-op
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
      - packages.operators.coreos.com
      - operator.ibm.com
      - operators.coreos.com
      - catalogsources.operators.coreos.com
    resources:
      - pods
      - pods/log
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
      - pods/exec
      - pods/portforward
      - endpoints
      - pods/status
      - jobs
      - secrets
      - commonservices
      - packagemanifests
      - configmaps
      - subscriptions
      - catalogsources
  - verbs:
      - get
      - list
    apiGroups:
      - postgresql.k8s.enterprisedb.io
    resources:
      - clusters