apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpfs-util-role
  namespace: cs-serv
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
      - deletecollection
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
      - packages.operators.coreos.com
      - operator.ibm.com
      - operators.coreos.com
      - catalogsources.operators.coreos.com
      - namespacescopes.operators.coreos.com
      - cert-manager.io
      - operatorgroups.operators.coreos.com
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings