apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpfs-util-cluster-role
  namespace: cs-op
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
rules:
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - ""
    resources:
      - namespaces