# Note there are no leading or trailing /'s
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  labels:
  clusterLabels:

global:
  operatorNamespace: operator-ns

