apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cs-db-backup-role
  namespace: <cs-db namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cs-db-data
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
      - route.openshift.io
    resources:
      - pods
      - pods/log
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
      - pods/exec
      - pods/portforward
      - endpoints
      - pods/status
      - jobs
      - secrets
      - configmaps
      - routes
  - verbs:
      - get
      - list
    apiGroups:
      - postgresql.k8s.enterprisedb.io
    resources:
      - clusters