kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-ibm-flink-operand
  namespace: "flinkNamespace"
  labels:
    component: cpfs3
spec:
  podSelector: 
    matchLabels:
      type: flink-standalone-kubernetes
  ingress:
    - ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 8081
      - protocol: TCP
        port: 9081
      - protocol: TCP
        port: 6122
      - protocol: TCP
        port: 6123
      - protocol: TCP
        port: 6124
  policyTypes:
    - Ingress