
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/instance: cs-ca-issuer
    app.kubernetes.io/managed-by: cert-manager-controller
    app.kubernetes.io/name: Issuer
    operator.ibm.com/managedByCsOperator: "true"
  name: cs-ca-issuer
  namespace: {{ .Values.serviceNamespace }}
spec:
  ca:
    secretName: cs-ca-certificate-secret

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/instance: cs-ss-issuer
    app.kubernetes.io/managed-by: cert-manager-controller
    app.kubernetes.io/name: Issuer
    operator.ibm.com/managedByCsOperator: "true"
  name: cs-ss-issuer
  namespace: {{ .Values.serviceNamespace }}
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: cs-ca-certificate
    app.kubernetes.io/managed-by: cert-manager-controller
    app.kubernetes.io/name: Certificate
    operator.ibm.com/managedByCsOperator: "true"
    ibm-cert-manager-operator/refresh-ca-chain: 'true'
  name: cs-ca-certificate
  namespace: {{ .Values.serviceNamespace }}
spec:
  secretName: cs-ca-certificate-secret
  secretTemplate:
    labels:
      ibm-cert-manager-operator/refresh-ca-chain: 'true'
  issuerRef:
    name: cs-ss-issuer
    kind: Issuer
  commonName: cs-ca-certificate
  isCA: true
  duration: 17520h0m0s
  renewBefore: 5840h0m0s
