apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  annotations:
    version: '-1'
  name: common-service
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    foundationservices.cloudpak.ibm.com: commonservice
spec:
  license:
    accept: {{ .Values.global.licenseAccept }}
  operatorNamespace: {{ .Values.global.operatorNamespace }}
  servicesNamespace: {{ .Values.global.instanceNamespace }}
  size: {{ .Values.commonServiceSpec.size }}
  storageClass: {{ .Values.global.blockStorageClass }}