apiVersion: v1
kind: ServiceAccount
metadata: 
  name: ibm-common-service-operator
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs.labels }}
      {{- with .Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}

{{- $chartName := .Chart.Name }}
{{- $operaterNamespace := .Values.global.operatorNamespace }}

{{- $namespaces := .Values.global.tetheredNamespaces | default list -}}
{{- $namespaces = append $namespaces .Values.global.operatorNamespace -}}
{{- if .Values.global.instanceNamespace }}
  {{- $namespaces = append $namespaces .Values.global.instanceNamespace }}
{{- end }}
{{- range $i := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: ibm-common-service-operator
  namespace: {{ $i }}
  labels:
    component-id: {{ $chartName }}
    {{- if $.Values.cpfs.labels }}
      {{- with $.Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
roleRef: 
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: ibm-common-service-operator
subjects:   
  - kind: ServiceAccount
    name: ibm-common-service-operator
    namespace: {{ $operaterNamespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: ibm-common-service-operator
  namespace: {{ $i }}
  labels:
    component-id: {{ $chartName }}
    {{- if $.Values.cpfs.labels }}
      {{- with $.Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
rules:   
  - apiGroups: 
      - ""
    resources: 
      - configmaps
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - operator.ibm.com
    resources: 
      - namespacescopes
    verbs: 
      - create
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups: 
      - cert-manager.io
    resources: 
      - certificates
      - issuers
    verbs: 
      - create
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups: 
      - apps
    resources: 
      - deployments
      - statefulsets
      - daemonsets
    verbs: 
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - operator.ibm.com
    resources: 
      - commonservices
      - commonservices/finalizers
      - commonservices/status
      - operandconfigs
      - operandregistries
      - operatorconfigs
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - operators.coreos.com
    resources: 
      - subscriptions
      - clusterserviceversions
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - ""
    resources: 
      - namespaces
    verbs: 
      - get
  - apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - get
      - list
      - delete
  - apiGroups: 
      - ""
    resources: 
      - secrets
      - services
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - ""
    resources: 
      - events
    verbs: 
      - create
      - get
      - patch
      - update
  - apiGroups: 
      - certmanager.k8s.io
    resources: 
      - certificates
      - issuers
    verbs: 
      - delete
  - apiGroups: 
      - monitoring.operator.ibm.com
    resources: 
      - exporters
      - prometheusexts
    verbs: 
      - delete
  - apiGroups: 
      - operator.ibm.com
    resources: 
      - operandrequests
      - operandbindinfos
      - cataloguis
      - helmapis
      - helmrepos
    verbs: 
      - delete
  - apiGroups: 
      - elasticstack.ibm.com
    resources: 
      - elasticstacks
    verbs: 
      - delete
  - apiGroups: 
      - ""
    resources: 
      - serviceaccounts
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - rbac.authorization.k8s.io
    resources: 
      - rolebindings
      - roles
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - operator.ibm.com
    resources: 
      - podpresets
    verbs: 
      - get
      - delete
      - list
  - apiGroups: 
      - ibmcpcs.ibm.com
    resources: 
      - secretshares
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgresql.k8s.enterprisedb.io
      - postgresql.cnpg.ibm.com
    resources:
      - clusters
    verbs:
      - get
      - list
      - update
  - apiGroups:
    - packages.operators.coreos.com
    resources:
    - packagemanifests
    verbs:
    - get
    - list
---
{{- end }}
