apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: Backup
metadata:
  name: <backup name>
  namespace: ibm-spectrum-fusion-ns
  finalizers:
    - backup
  labels:
    dp.isf.ibm.com/application-name: <application name>
    dp.isf.ibm.com/backuppolicy-name: <backup policy name>
    dp.isf.ibm.com/backupstoragelocation-name: <backup storage location name>
    dp.isf.ibm.com/provider-name: isf-backup-restore
spec:
  application: <application name>
  backupPolicy: <backup policy name>
  appCluster: <Cluster CR name only for backups on spoke cluster>