apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-rhbk-operator
  namespace: "csNamespace"
  labels:
    component: cpfs3
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
    to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          apiserver: "true"
  podSelector:
    matchLabels:
      name: "rhbk-operator"
  policyTypes:
  - Egress