apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zen5-backup-role
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
    resources:
      - pods
      - pods/log
      - configmaps
      - deployments
      - deployments/scale
      - pods/exec
      - pods/portforward
      - pods/status