apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: commonservice-backup
  namespace: velero
spec:
  schedule: 45 13 * * *
  template:
    ttl: 48h0m0s
    defaultVolumesToRestic: true
    storageLocation: bcdr-data-protection-app-1
    includeClusterResources: true
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    orLabelSelectors:
    - matchExpressions:
      - key: foundationservices.cloudpak.ibm.com
        operator: In
        values:
        - catalog
        - subscription
        - operand
        - zen-data
        - mongo-data
        - entitlementkey
        - commonservice
        - pull-secret
        - operatorgroup
        - zen
        - licensing
        - cert-manager
        - namespace
        - configmap
        - zen5
        - zen5-data
        - crd
        - lsr
        - lsr-data
        - cs-db-data
        - keycloak-data
