kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-backup-scripts
  namespace: ibm-common-services
  labels:
    foundationservices.cloudpak.ibm.com: mongo-data
spec:
  selector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: mongo-data
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: mongodump
        pre.hook.backup.velero.io/command: '["bash", "-c", "/scripts/mongo-backup.sh <ns> <sc> true"]'
        post.hook.restore.velero.io/command: '["bash", "-c", "/scripts/mongo-restore.sh <ns> true"]'
        pre.hook.backup.velero.io/wait-timeout: 300s
        pre.hook.backup.velero.io/exec-timeout: 300s
        pre.hook.backup.velero.io/timeout: 300s
      name: z-mongodb-br
      namespace: ibm-common-services
      labels:
        foundationservices.cloudpak.ibm.com: mongo-data
    spec:
      containers:
      - name: z-mongodb-br
        image: icr.io/cpopen/cpfs/cpfs-utils:4.1.0
        command: ["bash", "-c", "sleep infinity"]
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 512Mi
          requests:
            cpu: 200m
            ephemeral-storage: 128Mi
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: "/dump"
          subpath: dump
          name: mongodump
        - mountPath: "/cred/mongo-certs"
          name: icp-mongodb-client-cert
        - mountPath: "/cred/cluster-ca"
          name: cluster-ca-cert
        - mountPath: "/scripts"
          name: scripts
        - mountPath: "/work-dir"
          name: tmp-mongodb
        env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: icp-mongodb-admin
                key: user
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: icp-mongodb-admin
                key: password
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: mongo-z-backup-sa
      serviceAccountName: mongo-z-backup-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongodump
        persistentVolumeClaim:
          claimName: cs-mongodump
      - name: icp-mongodb-client-cert
        secret:
          secretName: icp-mongodb-client-cert
      - name: cluster-ca-cert
        secret:
          secretName: mongodb-root-ca-cert
      - name: scripts
        configMap:
          name: mongo-br-z-prep-script-cm
          defaultMode: 0777
      - name: tmp-mongodb
        emptyDir: {}