kind: Deployment
apiVersion: apps/v1
metadata:
  name: zen-backup
  namespace: <zenservice namespace>
  labels:
    foundationservices.cloudpak.ibm.com: zen-data
spec:
  selector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: zen-data
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: zendump
        pre.hook.backup.velero.io/command: '["sh", "-c", "/tmp/backup/backup_script.sh regular cron-job"]'
        pre.hook.backup.velero.io/timeout: 120s
        post.hook.backup.velero.io/command: '["sh", "-c", "rm -rf /user-home/zen-metastoredb-backup"]'
        post.hook.restore.velero.io/command: '["sh", "-c", "/tmp/backup/restore_script.sh regular cron-job"]'
      name: zen-backup
      namespace: <zenservice namespace>
      labels:
        foundationservices.cloudpak.ibm.com: zen-data
    spec:
        containers:
        - command:
          - sh
          - -c
          - sleep infinity
          image: icr.io/cpopen/cpfs/zen-metastoredb@sha256:8dfa918ef9329316cf8e7ea06a277dc4021e217da59fceffabfd73c2b1f808ae
          imagePullPolicy: IfNotPresent
          name: zen-metastore-backup-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /user-home
            name: user-home-mount
          - mountPath: /certs
            name: metastore-secret
          - mountPath: /tmp/backup
            name: zen-metastoredb-backup-scripts
        dnsPolicy: ClusterFirst
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        terminationGracePeriodSeconds: 30
        volumes:
        - name: user-home-mount
          persistentVolumeClaim:
            claimName: zen-backup-pvc
        - name: metastore-secret
          secret:
            defaultMode: 484
            secretName: metastore-secret
        - configMap:
            defaultMode: 511
            name: zen-metastoredb-backup-scripts
          name: zen-metastoredb-backup-scripts
