apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zen5-backup-role
  labels:
    foundationservices.cloudpak.ibm.com: zen5-data
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
    resources:
      - pods
      - pods/log
      - secrets
      - jobs
      - configmaps
      - deployments
      - deployments/scale
      - cronjobs
      - pods/exec
      - pods/portforward
      - endpoints
      - cronjob
      - pods/status
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - zen.cpd.ibm.com
      - postgresql.k8s.enterprisedb.io
    resources:
      - zenservice
      - zenservices
      - clusters
  - verbs:
      - get
    apiGroups:
      - ""
    resources:
      - configmaps