apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ibm-licensing-operator
  namespace: "licNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      name: "ibm-licensing-operator"
  policyTypes:
  - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
      to:
        - podSelector:
            matchLabels:
              apiserver: 'true'
          namespaceSelector: {}
