apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: child-license-reporter-recipe
  namespace: <lsr namespace>
  labels:
    dp.isf.ibm.com/parent-recipe: cpfs-singleton-parent-recipe
    dp.isf.ibm.com/parent-recipe-namespace: <fusion ns>
spec:
  appType: singleton
  groups:
    - includedResourceTypes:
        - ibmlicenseservicereporters.operator.ibm.com
        - role
        - rolebinding
        - serviceaccount
        - deployments
        - secrets
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-chart
      name: lsr-parent-resources
      type: resource
    - includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
        - clusterrole
        - clusterrolebinding
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-cluster
      name: lsr-parent-cluster-resources
      type: resource
    - backupRef: lsr-parent-resources
      includeClusterResources: true
      includedResourceTypes:
        - serviceaccount
        - role
        - rolebinding
      name: lsr-rbac-resources
      type: resource
    - backupRef: lsr-parent-resources
      includeClusterResources: true
      includedResourceTypes:
        - ibmlicenseservicereporters.operator.ibm.com
        - secrets
      name: lsr-workload-resources
      type: resource
    - backupRef: lsr-parent-resources
      includeClusterResources: true
      includedResourceTypes:
        - deployments
      name: lsr-deployment
      type: resource
    - includeClusterResources: true
      includedResourceTypes:
        - serviceaccount
        - role
        - rolebinding
        - configmaps
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-pre-deploy
      type: resource
    - includeClusterResources: true
      includedResourceTypes:
        - deployments
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-data-deployment
      type: resource
    - labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-volume
      type: volume
  hooks:
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: app.kubernetes.io/name=ibm-license-service-reporter
      name: lsr-operator-check
      namespace: <lsr namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: app.kubernetes.io/name=ibm-license-service-reporter-instance
      name: lsr-instance-check
      namespace: <lsr namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-deployment
      namespace: <lsr namespace>
      onError: fail
      selectResource: deployment
      timeout: 600
      type: check
    - labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-data
      namespace: <lsr namespace>
      onError: fail
      ops:
        - command: |
            ["/bin/bash", "-c", "rm -rf /lsr/lsr-backup/database; /lsr/br_lsr.sh <lsr namespace> backup"]
          container: lsr-backup-job
          name: backup
          timeout: 600
        - command: |
            ["/bin/bash", "-c", "/lsr/br_lsr.sh <lsr namespace> restore"]
          container: lsr-backup-job
          name: restore
          timeout: 2000
      selectResource: pod
      type: exec
  workflows:
    - failOn: any-error
      name: singleton-resources-backup
      sequence:
        - hook: lsr-data/backup
        - group: lsr-parent-resources
        - group: lsr-parent-cluster-resources
        - group: lsr-pre-deploy
        - group: lsr-volume
        - group: lsr-data-deployment
    - failOn: any-error
      name: singleton-resources-restore
      sequence:
        - group: lsr-rbac-resources
        - group: lsr-parent-cluster-resources
        - group: lsr-workload-resources
        - group: lsr-deployment
        - hook: lsr-operator-check/podReady
        - group: lsr-pre-deploy
        - group: lsr-volume
        - group: lsr-data-deployment
        - hook: lsr-deployment/podReady
        - hook: lsr-instance-check/podReady
        - hook: lsr-data/restore