apiVersion: application.isf.ibm.com/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: ibm-spectrum-fusion-ns
spec:
  enableDR: false
  includedNamespaces:
    - <cert manager namespace>
    - openshift-marketplace    
    - openshift-config
---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: BackupPolicy
metadata:
  name: cert-manager-backup-policy
  namespace: ibm-spectrum-fusion-ns
spec:
  backupStorageLocation: <storage_location>
  provider: isf-backup-restore
  retention:
    number: 5
    unit: days
  schedule:
    cron: '00 0  * * * '
    timezone: America/New_York
---

apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: cert-manager-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: cert-manager
  groups:
    - includeClusterResources: true
      includedResourceTypes:
        - certmanagerconfigs.operator.ibm.com
        - customresourcedefinitions.apiextensions.k8s.io
      labelSelector: foundationservices.cloudpak.ibm.com=cert-manager
      name: cert-manager-resources
      type: resource
    - backupRef: cert-manager-resources
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      name: cert-manager-crds
      type: resource
    - backupRef: cert-manager-resources
      includeClusterResources: true
      includedResourceTypes:
        - certmanagerconfigs.operator.ibm.com
      name: cert-manager-workload-resources
      type: resource
    - includedResourceTypes:
        - catalogsources.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=catalog
      name: cert-manager-catalog
      type: resource
    - includeClusterResources: true 
      labelSelector: foundationservices.cloudpak.ibm.com=namespace
      name: cert-manager-namespace
      type: resource
    - includedResourceTypes:
        - operatorgroups.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=operatorgroup
      name: cert-manager-operatorgroup
      type: resource
    - includedResourceTypes:
        - subscriptions.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=singleton-subscription
      name: cert-manager-subscription
      type: resource
  hooks:
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: app.kubernetes.io/name=cert-manager
      name: cert-manager-operator-check
      namespace: <cert manager namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
          name: podReady
          onError: fail
          timeout: 600
      name: cert-manager-webhook-check
      nameSelector: cert-manager-webhook
      namespace: <cert manager namespace>
      onError: fail
      selectResource: deployment
      timeout: 600
      type: check
  workflows:
    - failOn: essential-error
      name: backup
      sequence:
        - group: cert-manager-namespace
        - group: cert-manager-catalog
        - group: cert-manager-operatorgroup
        - group: cert-manager-subscription
        - group: cert-manager-resources
    - failOn: essential-error
      name: restore
      sequence:
        - group: cert-manager-namespace
        - group: cert-manager-catalog
        - group: cert-manager-operatorgroup
        - group: cert-manager-crds
        - group: cert-manager-workload-resources
        - group: cert-manager-subscription
        - hook: cert-manager-operator-check/podReady
        - hook: cert-manager-webhook-check/podReady
---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: PolicyAssignment
metadata:
  name: cert-manager-policy-assignment
  namespace: ibm-spectrum-fusion-ns
spec:
  application: cert-manager-application
  backupPolicy: cert-manager-backup-policy
  runNow: false
  recipe:
    apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
    name: cert-manager-recipe
    namespace: ibm-spectrum-fusion-ns