# permissions for end users to view commonservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonservice-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - commonservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - commonservices/status
  verbs:
  - get
