# permissions for end users to edit commonservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonservice-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - commonservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - commonservices/status
  verbs:
  - get
