apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-csNamespace-from-opNamespace-namespace
  namespace: "csNamespace"
  labels:
    component: cpfs3
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: "opNamespace"
