apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: access-to-zen-stopgap
  namespace: "csNamespace"
spec:
  ingress:
  - {}
  podSelector:
    matchExpressions:
    - key: app
      operator: Exists
  policyTypes:
  - Ingress
