apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-common-service-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-common-service-operator
  template:
    metadata:
      labels:
        name: ibm-common-service-operator
        app.kubernetes.io/instance: ibm-common-service-operator
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-common-service-operator
      containers:
        - name: ibm-common-service-operator
          image: quay.io/opencloudio/common-service-operator:latest
          command:
          - ibm-common-service-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-common-service-operator"
