apiVersion: application.isf.ibm.com/v1alpha1
kind: Application
metadata:
  name: lsr-application
  namespace: ibm-spectrum-fusion-ns
spec:
  enableDR: false
  includedNamespaces:
    - <lsr namespace>
    - openshift-marketplace    
    - openshift-config
---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: BackupPolicy
metadata:
  name: lsr-backup-policy
spec:
  backupStorageLocation: <storage_location>
  provider: isf-backup-restore
  retention:
    number: 5
    unit: days
  schedule:
    cron: '00 0  * * * '
    timezone: America/New_York
---

apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: lsr-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: license-service-reporter
  groups:
    - includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
        - secrets
        - ibmlicenseservicereporters.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-parent
      type: resource
    - backupRef: license-service-reporter-parent
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      name: license-service-reporter-crd
      type: resource
    - backupRef: license-service-reporter-parent
      includeClusterResources: true
      includedResourceTypes:
        - secrets
        - ibmlicenseservicereporters.operator.ibm.com
      name: license-service-reporter-instances
      type: resource
    - includedResourceTypes:
        - catalogsources.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-catalog
      type: resource
    - includeClusterResources: true
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-namespace
      type: resource
    - includedResourceTypes:
        - operatorgroups.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-operatorgroup
      type: resource
    - includedResourceTypes:
        - subscriptions.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-subscription
      type: resource
  hooks:
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      name: license-service-reporter-check
      labelSelector: app.kubernetes.io/name=ibm-license-service-reporter
      namespace: <lsr namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      name: license-service-reporter-instance-check
      labelSelector: app.kubernetes.io/instance=ibm-license-service-reporter
      namespace: <lsr namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
  workflows:
    - failOn: any-error
      name: backup
      sequence:
        - group: license-service-reporter-namespace
        - group: license-service-reporter-catalog
        - group: license-service-reporter-operatorgroup
        - group: license-service-reporter-parent
        - group: license-service-reporter-subscription
    - failOn: any-error
      name: restore
      sequence:
        - group: license-service-reporter-namespace
        - group: license-service-reporter-catalog
        - group: license-service-reporter-operatorgroup
        - group: license-service-reporter-crd
        - group: license-service-reporter-instances
        - group: license-service-reporter-subscription
        - hook: license-service-reporter-check/podReady
        - hook: license-service-reporter-instance-check/podReady
---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: PolicyAssignment
metadata:
  name: lsr-policy-assignment
  namespace: ibm-spectrum-fusion-ns
spec:
  application: lsr-application
  backupPolicy: lsr-backup-policy
  runNow: false
  recipe:
    apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
    name: lsr-recipe
    namespace: ibm-spectrum-fusion-ns