apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: cs-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: common-service
  groups:
    - includeClusterResources: true
      name: backup-parent-group
      type: resource
      includedResourceTypes:
        - secrets
        - certificates.cert-manager.io
        - issuers.cert-manager.io
        - customresourcedefinitions.apiextensions.k8s.io
        - ibmlicenseservicereporters.operator.ibm.com
        - deployments
        - serviceaccount
        - role
        - rolebinding
        - configmaps
        - catalogsources.operators.coreos.com
        - operatorgroups.operators.coreos.com
        - subscriptions.operators.coreos.com
        - jobs
        - commonservices.operator.ibm.com
        - operandrequests.operator.ibm.com
        - zenservices.zen.cpd.ibm.com
        - namespaces
      labelSelector: foundationservices.cloudpak.ibm.com
    - labelSelector: foundationservices.cloudpak.ibm.com
      name: backup-parent-volume
      type: volume
    - includeClusterResources: true
      backupRef: backup-parent-group
      includedResourceTypes:
        - secrets
        - certificates.cert-manager.io
        - issuers.cert-manager.io
        - customresourcedefinitions.apiextensions.k8s.io
      labelSelector: foundationservices.cloudpak.ibm.com=cert-manager
      name: cert-manager-resources
      type: resource
    - backupRef: backup-parent-group
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      name: cert-manager-crd
      type: resource
    - includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
        - secrets
        - ibmlicenseservicereporters.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-parent
      type: resource
      backupRef: backup-parent-group
    - backupRef: backup-parent-group
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      name: license-service-reporter-crd
      type: resource
    - backupRef: backup-parent-group
      includeClusterResources: true
      includedResourceTypes:
        - secrets
        - ibmlicenseservicereporters.operator.ibm.com
      name: license-service-reporter-instances
      type: resource
    - labelSelector: foundationservices.cloudpak.ibm.com=licensing
      name: licensing-resources
      type: resource
    - includeClusterResources: true
      backupRef: backup-parent-group
      includedResourceTypes:
        - deployments
        - serviceaccount
        - role
        - rolebinding
        - configmaps
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: license-service-reporter-resources
      type: resource
    - backupRef: backup-parent-group
      includeClusterResources: true
      includedResourceTypes:
        - serviceaccount
        - role
        - rolebinding
        - configmaps
      name: lsr-pre-deploy
      type: resource
    - backupRef: backup-parent-group
      includeClusterResources: true
      includedResourceTypes:
        - deployments
      name: lsr-deployment
      type: resource
    - labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-volume
      type: volume
      backupRef: backup-parent-volume
    - includedResourceTypes:
        - catalogsources.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=catalog
      name: common-services-catalogs
      type: resource
      backupRef: backup-parent-group
    - includedNamespaces:
        - openshift-config
      includedResourceTypes:
        - secrets
      labelSelector: foundationservices.cloudpak.ibm.com=pull-secret
      name: pull-secret
      type: resource
      backupRef: backup-parent-group
    - backupRef: backup-parent-group
      includedNamespaces:
        - openshift-config
      includedResourceTypes:
        - secrets
      labelSelector: foundationservices.cloudpak.ibm.com=pull-secret
      name: ow-pull-secret
      restoreOverwriteResources: true
      type: resource
    - includedResourceTypes:
        - configmaps
      labelSelector: foundationservices.cloudpak.ibm.com=configmap
      name: common-services-configmaps
      type: resource
      backupRef: backup-parent-group
    - includeClusterResources: true
      labelSelector: foundationservices.cloudpak.ibm.com=namespace
      name: common-services-namespace
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - operatorgroups.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=operatorgroup
      name: common-services-operatorgroups
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - subscriptions.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=subscription
      name: common-services-subscriptions
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - subscriptions.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=singleton-subscription
      name: singleton-subscriptions
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - subscriptions.operators.coreos.com
      labelSelector: foundationservices.cloudpak.ibm.com=lsr
      name: license-service-reporter-subscriptions
      type: resource
      backupRef: backup-parent-group
    - includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      labelSelector: foundationservices.cloudpak.ibm.com=crd
      name: commonservice-crd
      type: resource
      backupRef: backup-parent-group
    - includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions.apiextensions.k8s.io
      labelSelector: foundationservices.cloudpak.ibm.com=crd
      name: nss-crd
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - commonservices.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=commonservice
      name: commonservice-cr
      type: resource
      backupRef: backup-parent-group
    - includedResourceTypes:
        - operandrequests.operator.ibm.com
        - operandconfigs.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=operand
      name: odlm-resources
      type: resource
      backupRef: backup-parent-group
    - backupRef: backup-parent-group
      includedResourceTypes:
        - operandrequests.operator.ibm.com
        - operandconfigs.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=operand
      name: operand-resources
      restoreOverwriteResources: true
      type: resource
  hooks:
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 1200
      labelSelector: app.kubernetes.io/name=operand-deployment-lifecycle-manager
      name: odlm-check
      namespace: <operator namespace>
      onError: fail
      selectResource: pod
      timeout: 1200
      type: check
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: app.kubernetes.io/name=cert-manager
      name: cert-manager-operator-check
      namespace: ibm-cert-manager
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
          name: podReady
          onError: fail
          timeout: 600
      name: cert-manager-webhook-check
      nameSelector: cert-manager-webhook
      namespace: ibm-cert-manager
      onError: fail
      selectResource: deployment
      timeout: 600
      type: check
    - chks:
        - condition: '{$.status.phase} == {"Running"}'
          name: podReady
          onError: fail
          timeout: 600
      name: license-service-reporter-check
      labelSelector: app.kubernetes.io/name=ibm-license-service-reporter
      namespace: <lsr namespace>
      onError: fail
      selectResource: pod
      timeout: 600
      type: check
    - chks:
        - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
          name: podReady
          onError: fail
          timeout: 600
      labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-deployment
      namespace: <lsr namespace>
      onError: fail
      selectResource: deployment
      timeout: 600
      type: check
    - labelSelector: foundationservices.cloudpak.ibm.com=lsr-data
      name: lsr-data
      namespace: <lsr namespace>
      onError: fail
      ops:
        - command: |
            ["/bin/bash", "-c", "rm -rf /lsr/lsr-backup/database; /lsr/br_lsr.sh <lsr namespace> backup"]
          container: lsr-backup-job
          name: backup
          timeout: 600
        - command: |
            ["/bin/bash", "-c", "/lsr/br_lsr.sh <lsr namespace> restore"]
          container: lsr-backup-job
          name: restore
          timeout: 2000
      selectResource: pod
      type: exec
  workflows:
    - failOn: any-error
      name: backup
      sequence:
        - hook: lsr-data/backup
        - group: backup-parent-group
        - group: lsr-volume
    - failOn: any-error
      name: restore
      sequence:
        - group: common-services-namespace
        - group: pull-secret
        - group: ow-pull-secret
        - group: common-services-catalogs
        - group: common-services-operatorgroups
        - group: common-services-configmaps
        - group: commonservice-crd
        - group: cert-manager-crd
        - group: license-service-reporter-crd
        - group: singleton-subscriptions
        - group: commonservice-cr
        - hook: cert-manager-operator-check/podReady
        - hook: cert-manager-webhook-check/podReady
        - group: cert-manager-resources
        - group: licensing-resources
        - group: license-service-reporter-subscriptions
        - hook: license-service-reporter-check/podReady
        - group: license-service-reporter-instances
        - group: lsr-pre-deploy
        - group: lsr-volume
        - group: lsr-deployment
        - hook: lsr-deployment/podReady
        - hook: lsr-data/restore
        - group: common-services-subscriptions
        - hook: odlm-check/podReady
        - group: odlm-resources
        - group: operand-resources