apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs
  name: egress-zen-watchdog-post-requisite-job
  namespace: "zenNamespace"
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      component: zen-watchdog-post-requisite-job
  policyTypes:
  - Egress