apiVersion: batch/v1
kind: Job
metadata:
  name: label-cert-manager-job
  namespace: <operator namespace>
spec:
  template:
    metadata:
      name: label-cert-manager-job
      namespace: <operator namespace>
    spec:
      suspend: true
      restartPolicy: OnFailure
      containers:
      - command: ["/bin/bash", "-c", "/cs-br/label-cert-manager.sh --namespaces <comma delimited list of namespaces>"]
        image: icr.io/cpopen/cpfs/cpfs-utils:4.6.4
        imagePullPolicy: IfNotPresent
        name: cpfs-util
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 1536Mi
          requests:
            cpu: 200m
            ephemeral-storage: 128Mi
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: scripts
          mountPath: "/cs-br"
        - name: logs
          mountPath: /scripts/logs
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: label-cert-manager-job
      serviceAccountName: label-cert-manager-job
      terminationGracePeriodSeconds: 30
      volumes:
      - name: scripts
        configMap:
          name: label-cert-manager-job
          defaultMode: 0777
      - emptyDir: {}
        name: logs
