apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-singleton-cert-manager-job
  namespace: <cert manager namespace>
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: label-singleton-cert-manager-job
rules:
  - verbs:
      - get
      - list
      - update
      - patch
    apiGroups:
      - operators.coreos.com
      - operator.ibm.com
    resources:
      - namespaces
      - catalogsources
      - operatorgroups
      - subscriptions
      - certmanagerconfigs
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: label-singleton-cert-manager-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: label-singleton-cert-manager-job
subjects:
- kind: ServiceAccount
  name: label-singleton-cert-manager-job
  namespace: <cert manager namespace>
---

apiVersion: batch/v1
kind: Job
metadata:
  name: label-singleton-cert-manager-job
  namespace: <cert manager namespace>
spec:
  template:
    metadata:
      name: label-singleton-cert-manager-job
      namespace: <cert manager namespace>
    spec:
      suspend: true
      restartPolicy: OnFailure
      containers:
      - command: ["/bin/bash", "-c", "/scripts/velero/backup/cert-manager/label-singleton-cert-manager.sh --namespaces <cert manager namespace>"]

        image: icr.io/cpopen/cpfs/cpfs-utils:4.6.4
        imagePullPolicy: IfNotPresent
        name: cpfs-util
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 1536Mi
          requests:
            cpu: 200m
            ephemeral-storage: 128Mi
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: logs
          mountPath: /scripts/logs
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: label-singleton-cert-manager-job
      serviceAccountName: label-singleton-cert-manager-job
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: logs
