kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ibm-license-service-reporter-oidc-egress
  namespace: ibm-licensing-namespace
spec:
  podSelector:
    matchLabels:
      app: ibm-license-service-reporter-instance
  egress:
    - to:
        - ipBlock:
            cidr: ${OIDC-CIDF}
  policyTypes:
    - Egress