kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ibm-license-service-reporter-deny-all-egress
  namespace: "lsrNamespace"
spec:
  podSelector:
    matchLabels:
      app: ibm-license-service-reporter-instance
  policyTypes:
    - Egress