apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: ibm-common-service-operator-{{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs.labels }}
      {{- with .Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
    {{- if .Values.cpfs.clusterLabels }}
      {{- with .Values.cpfs.clusterLabels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
rules:   
  - apiGroups: 
      - ""
    resourceNames: 
      - common-service-maps
    resources: 
      - configmaps
    verbs: 
      - delete
      - update
  - apiGroups: 
      - ""
    resources: 
      - configmaps
    verbs: 
      - create
      - get
      - list
      - watch
      - update
  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get
  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs: 
      - get
      - list
  - apiGroups: 
      - config.openshift.io
    resources: 
      - infrastructures
    verbs: 
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: ibm-common-service-operator-{{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs.labels }}
      {{- with .Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
    {{- if .Values.cpfs.clusterLabels }}
      {{- with .Values.cpfs.clusterLabels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
roleRef: 
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: ibm-common-service-operator-{{ .Values.global.operatorNamespace }}
subjects:   
  - kind: ServiceAccount
    name: ibm-common-service-operator
    namespace: {{ .Values.global.operatorNamespace }}

---
