apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: ibm-common-service-operator
rules:   
  - apiGroups: 
      - ""
    resourceNames: 
      - common-service-maps
    resources: 
      - configmaps
    verbs: 
      - delete
      - update
  - apiGroups: 
      - ""
    resourceNames: 
      - cloud-native-postgresql-image-list
    resources: 
      - configmaps
    verbs: 
      - delete
  - apiGroups: 
      - ""
    resources: 
      - configmaps
    verbs: 
      - create
      - get
      - list
      - watch
      - update
  - apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - get
  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs: 
      - get
      - list
      - watch
  - apiGroups: 
      - admissionregistration.k8s.io
    resources: 
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - config.openshift.io
    resources: 
      - infrastructures
    verbs: 
      - get
  - apiGroups: 
      - rbac.authorization.k8s.io
    resources: 
      - clusterrolebindings
      - clusterroles
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: ibm-common-service-operator
roleRef: 
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: ibm-common-service-operator
subjects:   
  - kind: ServiceAccount
    name: ibm-common-service-operator
    namespace: {{ .Values.global.operatorNamespace }}

---
