apiVersion: batch/v1
kind: Job
metadata:
  name: lsr-restore-job
  namespace: <lsr namespace>
spec:
  template:
    spec:
        containers:
        - command:
          - sh
          - -c
          - /lsr/br_lsr.sh <lsr namespace> restore 
          image: icr.io/cpopen/cpfs/cpfs-utils:4.6.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: Always
          name: lsr-restore-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /lsr/lsr-backup
            name: lsr-backup-mount
          - name: scripts
            mountPath: "/lsr"
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: lsr-backup-sa
        serviceAccountName: lsr-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: lsr-backup-mount
          persistentVolumeClaim:
            claimName: lsr-backup-pvc
        - name: scripts
          configMap:
            name: lsr-br-configmap
            defaultMode: 0777