#only uncomment the backup storage location secret and CR if one is not already created. 
#fusion setup script creates one by default with the same info and different applications can share
# kind: Secret
# apiVersion: v1
# metadata:
#   name: <location name>-secret-0
#   namespace: <fusion ns>
#   labels:
#     dp.isf.ibm.com/ownedBy: fbsl
#     dp.isf.ibm.com/provider-name: isf-backup-restore
# data:
#   access-key-id: <base 64 encoded access key id>
#   secret-access-key: <base 64 encoded secret access key>
# type: Opaque

# ---

# apiVersion: data-protection.isf.ibm.com/v1alpha1
# kind: BackupStorageLocation
# metadata:
#   name: <location name>
#   namespace: <fusion ns>
#   finalizers:
#     - backupstoragelocation
#   labels:
#     dp.isf.ibm.com/backupstoragelocation-type: ibm
#     dp.isf.ibm.com/provider-name: isf-backup-restore
# spec:
#   credentialName: <location name>-secret-0
#   params:
#     bucket: <bucket name>
#     endpoint: <s3 url>
#   provider: isf-backup-restore
#   type: ibm
# ---
apiVersion: application.isf.ibm.com/v1alpha1
kind: Application
metadata:
  name: cs-singleton
  namespace: <fusion ns>
spec:
  enableDR: false
  includedNamespaces:
    #default namespaces for licensing, cert manager, and reporter operators
    #- ibm-cert-manager
    #- ibm-licensing
    #- ibm-ls-reporter
    - <cert manager namespace>
    - <licensing namespace>
    - <lsr namespace>
    - openshift-marketplace
    - openshift-config

---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: BackupPolicy
metadata:
  name: cs-singleton-backup-policy
  namespace: <fusion ns>
spec:
  backupStorageLocation: <location name>
  provider: isf-backup-restore
  retention:
    number: 5
    unit: days
  schedule:
    cron: '00 0  * * * '
    timezone: America/New_York

---

apiVersion: data-protection.isf.ibm.com/v1alpha1
kind: PolicyAssignment
metadata:
  name: cs-singleton-policy-assignment
  namespace: <fusion ns>
spec:
  application: cs-singleton
  backupPolicy: cs-singleton-backup-policy
  recipe:
    apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
    name: cpfs-singleton-parent-recipe
    namespace: <fusion ns>
  runNow: false