apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v3",
          "kind": "CommonService",
          "metadata": {
            "name": "example-commonservice"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-common-service-operator.v3.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CommonService is the Schema for the commonservices API
      displayName: CommonService
      kind: CommonService
      name: commonservices.operator.ibm.com
      version: v3
  description: |-
    This operator is a bridge to connect CloudPaks and ODLM/Common Services, and it can be also installed in standalone mode.

    Following resource will be created when this operator installed

    * ODLM will be installed in all namespaces mode
    * `ibm-common-services` namespace will be created
    * `OperandRegistry` and `OperandConfig` of Common Services will be created under `ibm-common-services` namespace

    # Install Individual Common Services

    Install individual common services by creating an `OperandRequest`.

    ```yaml
    apiVersion: operator.ibm.com/v1alpha1
    kind: OperandRequest
    metadata:
      name: common-service
      namespace: ibm-common-services
    spec:
      requests:
        - operands:
            - name: ibm-cert-manager-operator
            - name: ibm-mongodb-operator
            - name: ibm-iam-operator
            - name: ibm-monitoring-exporters-operator
            - name: ibm-monitoring-prometheusext-operator
            - name: ibm-monitoring-grafana-operator
            - name: ibm-healthcheck-operator
            - name: ibm-management-ingress-operator
            - name: ibm-licensing-operator
            - name: ibm-metering-operator
            - name: ibm-commonui-operator
            - name: ibm-elastic-stack-operator
            - name: ibm-ingress-nginx-operator
            - name: ibm-auditlogging-operator
            - name: ibm-platform-api-operator
            - name: ibm-helm-api-operator
            - name: ibm-helm-repo-operator
            - name: ibm-catalog-ui-operator
          registry: common-service
    ```

    Open the OpenShift Web Console, click the plus button in top right corner, then copy the above `OperandRequest` into the editor and create.
  displayName: IBM Common Service Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: ibm-common-service-operator
      deployments:
      - name: ibm-common-service-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-common-service-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-common-service-operator
            spec:
              containers:
              - command:
                - ibm-common-service-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-common-service-operator
                image: quay.io/opencloudio/common-service-operator:latest
                imagePullPolicy: Always
                name: ibm-common-service-operator
                resources: {}
              serviceAccountName: ibm-common-service-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  maintainers:
  - email: supports@ibm.com
    name: IBM Support
  maturity: alpha
  provider:
    name: IBM
  version: 3.4.0
