apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v3",
          "kind": "CommonService",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "ibm-common-service-operator",
              "app.kubernetes.io/managed-by": "ibm-common-service-operator",
              "app.kubernetes.io/name": "ibm-common-service-operator"
            },
            "name": "example-commonservice"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
    containerImage: quay.io/opencloudio/common-service-operator:latest
    createdAt: "2020-04-06T11:28:16Z"
    description: The IBM Common Service Operator is used to deploy IBM Common Services
    repository: https://github.com/IBM/ibm-common-service-operator
    support: IBM
  name: ibm-common-service-operator.v3.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CommonService is the Schema for the commonservices API
      displayName: CommonService
      kind: CommonService
      name: commonservices.operator.ibm.com
      version: v3
  description: The `ibm-common-service-operator` is a bridge to connect IBM Cloud Paks and Operand Deployment Lifecycle Manager (ODLM) with IBM Cloud Platform Common Services. You can also install the `ibm-common-service-operator` in stand-alone mode.

    When you install this operator, the operator completes the following tasks:

    - Installs ODLM in all namespaces mode
    - Creates the `ibm-common-services` namespace
    - Creates the Common Services `OperandRegistry` and `OperandConfig` in the `ibm-common-services` namespace

    For more information about installing this operator and other Common Services operators, see [Installer documentation](http://ibm.biz/cpcs_opinstall). If you are using this operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak to learn more about how to install and use the operator service. For more information about IBM Cloud Paks, see [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks).

    For more information about the available IBM Cloud Platform Common Services, see the [IBM Knowledge Center](http://ibm.biz/cpcsdocs).

    ## Supported platforms

    Red Hat OpenShift Container Platform 4.3 or newer installed on one of the following platforms:

       - Linux x86_64
       - Linux on Power (ppc64le)

    ## Operator versions

     - 3.4.0

    ## Prerequisites

    Before you install this operator, you need to first install the operator prerequisites:

    - For the list of prerequisites for installing the operator, see the IBM Knowledge Center [Preparing to install services documentation](http://ibm.biz/cpcs_opinstprereq).

    ## Documentation

    - If you are using the operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak. For a list of IBM Cloud Paks, see [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks).
    - If you are using the operator in stand-alone mode or with an IBM Containerized Software, see the IBM Cloud Platform Common Services Knowledge Center [Installer documentation](http://ibm.biz/cpcs_opinstall).  
  displayName: IBM Common Service Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: ibm-common-service-operator
      deployments:
      - name: ibm-common-service-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-common-service-operator
          strategy: {}
          template:
            metadata:
              annotations:
                productID: 068a62892a1e4db39641342e592daa25
                productMetric: FREE
                productName: IBM Cloud Platform Common Services
                productVersion: 3.4.0
              labels:
                app.kubernetes.io/instance: ibm-common-service-operator
                app.kubernetes.io/managed-by: ibm-common-service-operator
                app.kubernetes.io/name: ibm-common-service-operator
                name: ibm-common-service-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - ppc64le
                        - s390x
              containers:
              - command:
                - ibm-common-service-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-common-service-operator
                image: quay.io/opencloudio/common-service-operator:latest
                imagePullPolicy: Always
                name: ibm-common-service-operator
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  privileged: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
              serviceAccountName: ibm-common-service-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  maintainers:
  - email: supports@ibm.com
    name: IBM Support
  maturity: alpha
  provider:
    name: IBM
  version: 3.4.0
