imagePullPrefix: icr.io
imagePullSecret: ibm-entitlement-key

# Note there are no leading or trailing /'s
imageRegistryNamespaceOperator: cpopen
imageRegistryNamespaceOperand: cpopen/cpfs

operatorVersion: 4.11.0

# other configuration you think you might need for your operator
# following are examples, not required:
operatorNamespace: <operator namespace>
servicesNamespace: <services namespace>
operatorImage: common-service-operator

# CR configurations

commonServiceSpec:
  license:
    accept: false
  size: starterset
