imagePullPrefix: icr.io
imagePullSecret: ibm-entitlement-key
imageRegistryNamespaceOperand: cpopen/cpfs
imageRegistryNamespaceOperator: cpopen
operatorImage: ibm-common-service-operator
operatorNamespace: operators
operatorVersion: latest
servicesNamespace: service

commonservicesOperatorIbmComCrd: {}
ibmCommonServiceOperatorCr: {}
ibmCommonServiceOperatorCrb: {}
ibmCommonServiceOperatorDeployment: {}
ibmCommonServiceOperatorRb: {}
ibmCommonServiceOperatorRole: {}
ibmCommonServiceOperatorSa: {}
mutatingWebhookConfigurationMutatingwebhookconfiguration: {}
selfsignedIssuerIssuer: {}
servingCertCertificate: {}
validatingWebhookConfigurationValidatingwebhookconfiguration: {}
webhookServiceSvc: {}

