imagePullPrefix: icr.io
imagePullSecret: ibm-entitlement-key

# Note there are no leading or trailing /'s
imageRegistryNamespaceOperator: cpopen
imageRegistryNamespaceOperand: cpopen/cpfs

# version tag for operator
operatorVersion: '4.11.0'

# other configuration you think you might need for your operator
# following are examples, not required:
operatorNamespace: operators
servicesNamespace: services
operatorImage: ibm-common-service-operator