apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  labels:
    dp.isf.ibm.com/parent-recipe: cpfs-parent-recipe
    dp.isf.ibm.com/parent-recipe-namespace: <parent recipe namespace>
  name: nss-child-recipe
  namespace: <child recipe namespace>
spec:
  appType: common-service
  groups:
    - includeClusterResources: true
      includedResourceTypes:
        - clusterrole
        - clusterrolebinding
        - customresourcedefinitions.apiextensions.k8s.io
      labelSelector: foundationservices.cloudpak.ibm.com=nss-cluster
      name: nss-cluster-resources
      type: resource
    - includeClusterResources: true
      includedResourceTypes:
        - role
        - rolebinding
        - serviceaccount
        - deployments
        - secrets
        - namespacescopes.operator.ibm.com
      labelSelector: foundationservices.cloudpak.ibm.com=nss
      name: nss-resources
      type: resource
    - backupRef: nss-resources
      includedResourceTypes:
        - serviceaccount
        - role
        - rolebinding
        - secrets
      name: nss-rbac-resources
      type: resource
    - backupRef: nss-resources
      includedResourceTypes:
        - namespacescopes.operator.ibm.com
      name: nss-cr
      type: resource
    - backupRef: nss-resources
      includedResourceTypes:
        - deployments
      name: nss-deployment
      type: resource
  hooks:
    - chks:
        - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
          name: podReady
          onError: fail
          timeout: 600
      name: nss-check
      nameSelector: ibm-namespace-scope-operator
      namespace: <operator_ns>
      onError: fail
      selectResource: deployment
      timeout: 600
      type: check
  workflows:
    - name: chart-backup
      priority: 0
      sequence:
        - group: nss-cluster-resources
        - group: nss-resources
    - name: chart-restore
      priority: 10
      sequence:
        - group: nss-cluster-resources
        - group: nss-rbac-resources
        - group: nss-cr
        - group: nss-deployment
        - hook: nss-check/podReady