apiVersion: batch/v1
kind: Job
metadata:
  name: label-cpfs-job
  namespace: <operator namespace>
  labels:
    foundationservices.cloudpak.ibm.com: label-cpfs-job
spec:
  template:
    metadata:
      name: label-cpfs-job
      namespace: <operator namespace>
      labels:
        foundationservices.cloudpak.ibm.com: label-cpfs-job
    spec:
      suspend: true
      restartPolicy: OnFailure
      containers:
      - command: ["/bin/bash", "-c", "/scripts/velero/backup/common-service/label-common-service.sh"]
        image: icr.io/cpopen/cpfs/cpfs-utils:4.6.4
        imagePullPolicy: IfNotPresent
        name: cpfs-util
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 1536Mi
          requests:
            cpu: 200m
            ephemeral-storage: 128Mi
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: logs
          mountPath: /scripts/logs
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: label-cpfs-job-sa
      serviceAccountName: label-cpfs-job-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: logs
