apiVersion: batch/v1
kind: Job
metadata:
  name: label-bedrock-job
  namespace: cs-op
spec:
  template:
    metadata:
      name: label-bedrock-job
      namespace: cs-op
    spec:
      suspend: true
      restartPolicy: OnFailure
      containers:
      - command: ["/bin/bash", "-c", "/cs-br/label-common-service.sh --operator-ns cs-op --services-ns cs-serv --tethered-ns cs-ten1,cs-ten2 --cert-manager-ns ibm-cert-manager --licensing-ns ibm-licensing --lsr-ns ibm-lsr --enable-default-catalog-ns --additional-catalog-sources ibm-operator-catalog-latest,opencloud-operators-cd"]
        image: icr.io/cpopen/cpfs/cpfs-utils:4.6.4
        imagePullPolicy: IfNotPresent
        name: cpfs-util
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 512Mi
            memory: 1536Mi
          requests:
            cpu: 200m
            ephemeral-storage: 128Mi
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: scripts
          mountPath: "/cs-br"
        - name: logs
          mountPath: /scripts/logs
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: label-bedrock-job
      serviceAccountName: label-bedrock-job
      terminationGracePeriodSeconds: 30
      volumes:
      - name: scripts
        configMap:
          name: label-bedrock-job
          defaultMode: 0777
      - emptyDir: {}
        name: logs
