apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-ibm-com-v1alpha1-operandrequest
  failurePolicy: Ignore
  name: moperandrequest.kb.io
  rules:
  - apiGroups:
    - operator.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operandrequests
  sideEffects: None
